var annotated_dup =
[
    [ "mimicpp", "d1/d11/namespacemimicpp.html", [
      [ "call", "dc/d2e/namespacemimicpp_1_1call.html", [
        [ "Info", "d4/d44/classmimicpp_1_1call_1_1_info.html", "d4/d44/classmimicpp_1_1call_1_1_info" ],
        [ "info_for_signature", "d8/d5b/structmimicpp_1_1call_1_1info__for__signature.html", null ],
        [ "info_for_signature< Return(Args...)>", "d8/d5b/structmimicpp_1_1call_1_1info__for__signature.html", "d8/d5b/structmimicpp_1_1call_1_1info__for__signature" ]
      ] ],
      [ "custom", "d4/d84/namespacemimicpp_1_1custom.html", [
        [ "matcher_traits", "d5/d5a/structmimicpp_1_1custom_1_1matcher__traits.html", null ],
        [ "Printer", "da/d68/classmimicpp_1_1custom_1_1_printer.html", null ]
      ] ],
      [ "expectation_policies", "d0/d91/namespacemimicpp_1_1expectation__policies.html", [
        [ "ArgsRequirement", "d8/dbc/classmimicpp_1_1expectation__policies_1_1_args_requirement.html", "d8/dbc/classmimicpp_1_1expectation__policies_1_1_args_requirement" ],
        [ "Category", "d4/d44/classmimicpp_1_1expectation__policies_1_1_category.html", "d4/d44/classmimicpp_1_1expectation__policies_1_1_category" ],
        [ "Constness", "db/dbc/classmimicpp_1_1expectation__policies_1_1_constness.html", "db/dbc/classmimicpp_1_1expectation__policies_1_1_constness" ],
        [ "InitFinalize", "d2/d77/classmimicpp_1_1expectation__policies_1_1_init_finalize.html", "d2/d77/classmimicpp_1_1expectation__policies_1_1_init_finalize" ],
        [ "matcher_matches_fn", "d6/de9/structmimicpp_1_1expectation__policies_1_1matcher__matches__fn.html", "d6/de9/structmimicpp_1_1expectation__policies_1_1matcher__matches__fn" ],
        [ "ReturnsResultOf", "dd/d59/classmimicpp_1_1expectation__policies_1_1_returns_result_of.html", "dd/d59/classmimicpp_1_1expectation__policies_1_1_returns_result_of" ],
        [ "SideEffectAction", "d5/d8f/classmimicpp_1_1expectation__policies_1_1_side_effect_action.html", "d5/d8f/classmimicpp_1_1expectation__policies_1_1_side_effect_action" ],
        [ "Throws", "d8/d34/classmimicpp_1_1expectation__policies_1_1_throws.html", "d8/d34/classmimicpp_1_1expectation__policies_1_1_throws" ]
      ] ],
      [ "format", "d3/d54/namespacemimicpp_1_1format.html", [
        [ "formatter< mimicpp::Constness, mimicpp::CharT >", "d2/d9b/structmimicpp_1_1format_1_1formatter_3_01mimicpp_1_1_constness_00_01mimicpp_1_1_char_t_01_4.html", "d2/d9b/structmimicpp_1_1format_1_1formatter_3_01mimicpp_1_1_constness_00_01mimicpp_1_1_char_t_01_4" ],
        [ "formatter< mimicpp::ValueCategory, mimicpp::CharT >", "db/dc9/structmimicpp_1_1format_1_1formatter_3_01mimicpp_1_1_value_category_00_01mimicpp_1_1_char_t_01_4.html", "db/dc9/structmimicpp_1_1format_1_1formatter_3_01mimicpp_1_1_value_category_00_01mimicpp_1_1_char_t_01_4" ]
      ] ],
      [ "sequence", "d8/dce/namespacemimicpp_1_1sequence.html", [
        [ "rating", "de/d81/structmimicpp_1_1sequence_1_1rating.html", "de/d81/structmimicpp_1_1sequence_1_1rating" ]
      ] ],
      [ "stacktrace", "df/d4b/namespacemimicpp_1_1stacktrace.html", [
        [ "backend_traits", "da/d77/structmimicpp_1_1stacktrace_1_1backend__traits.html", null ],
        [ "backend_traits< mimicpp::stacktrace::NullBackend >", "da/d77/structmimicpp_1_1stacktrace_1_1backend__traits.html", "da/d77/structmimicpp_1_1stacktrace_1_1backend__traits" ],
        [ "find_backend", "dc/dc2/structmimicpp_1_1stacktrace_1_1find__backend.html", "dc/dc2/structmimicpp_1_1stacktrace_1_1find__backend" ],
        [ "NullBackend", "d0/d60/classmimicpp_1_1stacktrace_1_1_null_backend.html", null ]
      ] ],
      [ "always_false", "d5/d8e/structmimicpp_1_1always__false.html", null ],
      [ "BasicExpectation", "d3/d4a/classmimicpp_1_1_basic_expectation.html", "d3/d4a/classmimicpp_1_1_basic_expectation" ],
      [ "BasicExpectationBuilder", "d5/de1/classmimicpp_1_1_basic_expectation_builder.html", "d5/de1/classmimicpp_1_1_basic_expectation_builder" ],
      [ "BasicReporter", "d4/d56/classmimicpp_1_1_basic_reporter.html", "d4/d56/classmimicpp_1_1_basic_reporter" ],
      [ "call_convention_traits", "d3/db5/structmimicpp_1_1call__convention__traits.html", null ],
      [ "call_convention_traits< detail::default_call_convention >", "d3/db5/structmimicpp_1_1call__convention__traits.html", "d3/db5/structmimicpp_1_1call__convention__traits" ],
      [ "CallReport", "dc/dd0/classmimicpp_1_1_call_report.html", "dc/dd0/classmimicpp_1_1_call_report" ],
      [ "case_insensitive_t", "d2/dd4/structmimicpp_1_1case__insensitive__t.html", null ],
      [ "ControlPolicy", "dc/db2/classmimicpp_1_1_control_policy.html", "dc/db2/classmimicpp_1_1_control_policy" ],
      [ "DefaultReporter", "d3/d32/classmimicpp_1_1_default_reporter.html", "d3/d32/classmimicpp_1_1_default_reporter" ],
      [ "Error", "db/d10/classmimicpp_1_1_error.html", "db/d10/classmimicpp_1_1_error" ],
      [ "Expectation", "d3/d1c/classmimicpp_1_1_expectation.html", "d3/d1c/classmimicpp_1_1_expectation" ],
      [ "ExpectationCollection", "d5/d86/classmimicpp_1_1_expectation_collection.html", "d5/d86/classmimicpp_1_1_expectation_collection" ],
      [ "ExpectationReport", "dd/d62/classmimicpp_1_1_expectation_report.html", "dd/d62/classmimicpp_1_1_expectation_report" ],
      [ "GreedySequence", "db/d43/classmimicpp_1_1_greedy_sequence.html", null ],
      [ "IReporter", "dd/df0/classmimicpp_1_1_i_reporter.html", "dd/df0/classmimicpp_1_1_i_reporter" ],
      [ "is_character", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< char16_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< char32_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< char8_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< signed char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< unsigned char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_character< wchar_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "is_overload_set", "dd/df5/structmimicpp_1_1is__overload__set.html", null ],
      [ "is_overload_set< First >", "dd/df5/structmimicpp_1_1is__overload__set.html", null ],
      [ "is_overloadable_with", "d4/dd6/structmimicpp_1_1is__overloadable__with.html", null ],
      [ "LazySequence", "db/d46/classmimicpp_1_1_lazy_sequence.html", null ],
      [ "LifetimeWatcher", "db/d98/classmimicpp_1_1_lifetime_watcher.html", "db/d98/classmimicpp_1_1_lifetime_watcher" ],
      [ "MatchReport", "db/d11/classmimicpp_1_1_match_report.html", "db/d11/classmimicpp_1_1_match_report" ],
      [ "Mock", "d2/d48/classmimicpp_1_1_mock.html", "d2/d48/classmimicpp_1_1_mock" ],
      [ "PredicateMatcher", "dc/d5e/classmimicpp_1_1_predicate_matcher.html", "dc/d5e/classmimicpp_1_1_predicate_matcher" ],
      [ "priority_tag", "d1/d9f/structmimicpp_1_1priority__tag.html", null ],
      [ "priority_tag< 0 >", "d1/d9f/structmimicpp_1_1priority__tag.html", null ],
      [ "RelocationWatcher", "da/d45/classmimicpp_1_1_relocation_watcher.html", "da/d45/classmimicpp_1_1_relocation_watcher" ],
      [ "ScopedExpectation", "d6/dc0/classmimicpp_1_1_scoped_expectation.html", "d6/dc0/classmimicpp_1_1_scoped_expectation" ],
      [ "signature_add_noexcept", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
      [ "signature_add_noexcept< Return(Params...) && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) const & >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) const && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) const &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) const &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) const >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) const noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...) noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...)& >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...)>", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) const & >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) const && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) const &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) const &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) const >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) const noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...) noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...)& >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_add_noexcept< Return(Params...,...)>", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", "dd/db4/structmimicpp_1_1signature__add__noexcept" ],
      [ "signature_call_convention", "dc/d9a/structmimicpp_1_1signature__call__convention.html", null ],
      [ "signature_call_convention< Signature >", "dc/d9a/structmimicpp_1_1signature__call__convention.html", "dc/d9a/structmimicpp_1_1signature__call__convention" ],
      [ "signature_const_qualification", "d2/de2/structmimicpp_1_1signature__const__qualification.html", null ],
      [ "signature_decay", "db/df4/structmimicpp_1_1signature__decay.html", "db/df4/structmimicpp_1_1signature__decay" ],
      [ "signature_is_noexcept", "d9/d28/structmimicpp_1_1signature__is__noexcept.html", null ],
      [ "signature_param_list", "d0/df4/structmimicpp_1_1signature__param__list.html", null ],
      [ "signature_param_list< Return(Params...)>", "d0/df4/structmimicpp_1_1signature__param__list.html", "d0/df4/structmimicpp_1_1signature__param__list" ],
      [ "signature_param_type", "db/dd5/structmimicpp_1_1signature__param__type.html", null ],
      [ "signature_param_type< index, Return(Params...)>", "db/dd5/structmimicpp_1_1signature__param__type.html", null ],
      [ "signature_ref_qualification", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_ref_qualification< Return(Params...) && >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_ref_qualification< Return(Params...)& >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_ref_qualification< Return(Params...)>", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_ref_qualification< Return(Params...,...) && >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_ref_qualification< Return(Params...,...)& >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_ref_qualification< Return(Params...,...)>", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "signature_remove_call_convention", "dc/d70/structmimicpp_1_1signature__remove__call__convention.html", "dc/d70/structmimicpp_1_1signature__remove__call__convention" ],
      [ "signature_remove_const_qualifier", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
      [ "signature_remove_const_qualifier< Return(Params...) && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) const & >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) const && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) const &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) const &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) const >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) const noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...) noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...)& >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...)>", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) const & >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) const && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) const &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) const &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) const >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) const noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...) noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...)& >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Return(Params...,...)>", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_const_qualifier< Signature >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier" ],
      [ "signature_remove_noexcept", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
      [ "signature_remove_noexcept< Return(Params...) && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) const & >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) const && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) const &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) const &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) const >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) const noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...) noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...)& >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...)>", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) const & >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) const && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) const &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) const &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) const >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) const noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...) noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...)& >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Return(Params...,...)>", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_noexcept< Signature >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", "d4/db7/structmimicpp_1_1signature__remove__noexcept" ],
      [ "signature_remove_ref_qualifier", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
      [ "signature_remove_ref_qualifier< Return(Params...) && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) const & >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) const && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) const &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) const &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) const >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) const noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...) noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...)& >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...)>", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) const & >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) const && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) const &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) const &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) const >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) const noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...) noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...)& >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Return(Params...,...)>", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_remove_ref_qualifier< Signature >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier" ],
      [ "signature_return_type", "d4/d96/structmimicpp_1_1signature__return__type.html", null ],
      [ "signature_return_type< Return(Params...)>", "d4/d96/structmimicpp_1_1signature__return__type.html", "d4/d96/structmimicpp_1_1signature__return__type" ],
      [ "signature_return_type< Return(Params...,...)>", "d4/d96/structmimicpp_1_1signature__return__type.html", "d4/d96/structmimicpp_1_1signature__return__type" ],
      [ "Stacktrace", "db/d18/classmimicpp_1_1_stacktrace.html", "db/d18/classmimicpp_1_1_stacktrace" ],
      [ "state_applicable", "d0/d12/structmimicpp_1_1state__applicable.html", "d0/d12/structmimicpp_1_1state__applicable" ],
      [ "state_inapplicable", "d7/dd2/structmimicpp_1_1state__inapplicable.html", "d7/dd2/structmimicpp_1_1state__inapplicable" ],
      [ "state_saturated", "de/d68/structmimicpp_1_1state__saturated.html", "de/d68/structmimicpp_1_1state__saturated" ],
      [ "string_case_fold_converter", "d4/d2d/structmimicpp_1_1string__case__fold__converter.html", null ],
      [ "string_case_fold_converter< char >", "d4/d2d/structmimicpp_1_1string__case__fold__converter.html", "d4/d2d/structmimicpp_1_1string__case__fold__converter" ],
      [ "string_traits", "d1/dee/structmimicpp_1_1string__traits.html", null ],
      [ "string_traits< std::basic_string< Char, Traits, Allocator > >", "d1/dee/structmimicpp_1_1string__traits.html", "d1/dee/structmimicpp_1_1string__traits" ],
      [ "string_traits< std::basic_string_view< Char, Traits > >", "d1/dee/structmimicpp_1_1string__traits.html", "d1/dee/structmimicpp_1_1string__traits" ],
      [ "string_traits< T >", "d1/dee/structmimicpp_1_1string__traits.html", "d1/dee/structmimicpp_1_1string__traits" ],
      [ "type_list", "db/dc6/structmimicpp_1_1type__list.html", null ],
      [ "uint_with_size", "d7/da0/structmimicpp_1_1uint__with__size.html", null ],
      [ "uint_with_size< 1u >", "d7/da0/structmimicpp_1_1uint__with__size.html", "d7/da0/structmimicpp_1_1uint__with__size" ],
      [ "uint_with_size< 2u >", "d7/da0/structmimicpp_1_1uint__with__size.html", "d7/da0/structmimicpp_1_1uint__with__size" ],
      [ "uint_with_size< 4u >", "d7/da0/structmimicpp_1_1uint__with__size.html", "d7/da0/structmimicpp_1_1uint__with__size" ],
      [ "uint_with_size< 8u >", "d7/da0/structmimicpp_1_1uint__with__size.html", "d7/da0/structmimicpp_1_1uint__with__size" ],
      [ "Watched", "d3/d5d/classmimicpp_1_1_watched.html", "d3/d5d/classmimicpp_1_1_watched" ],
      [ "WildcardMatcher", "db/de6/classmimicpp_1_1_wildcard_matcher.html", "db/de6/classmimicpp_1_1_wildcard_matcher" ]
    ] ]
];