var hierarchy =
[
    [ "mimicpp::CallReport::Arg", "dc/d03/classmimicpp_1_1_call_report_1_1_arg.html", null ],
    [ "mimicpp::expectation_policies::ArgsRequirement< Matcher, MatchesStrategy, DescribeStrategy >", "d8/dbc/classmimicpp_1_1expectation__policies_1_1_args_requirement.html", null ],
    [ "mimicpp::stacktrace::backend_traits< Backend >", "da/d77/structmimicpp_1_1stacktrace_1_1backend__traits.html", null ],
    [ "mimicpp::stacktrace::backend_traits< mimicpp::stacktrace::NullBackend >", "da/d77/structmimicpp_1_1stacktrace_1_1backend__traits.html", null ],
    [ "Base", null, [
      [ "mimicpp::detail::BasicWatched< Base, Watchers... >", null, [
        [ "mimicpp::Watched< Base, Watchers >", "d3/d5d/classmimicpp_1_1_watched.html", null ]
      ] ],
      [ "mimicpp::detail::BasicWatched< Base, Watchers... >", null, null ]
    ] ],
    [ "mimicpp::BasicExpectationBuilder< timesConfigured, SequenceConfig, Signature, FinalizePolicy, Policies >", "d5/de1/classmimicpp_1_1_basic_expectation_builder.html", null ],
    [ "mimicpp::detail::BasicMock< FirstSignature >", null, [
      [ "mimicpp::Mock< FirstSignature, OtherSignatures >", "d2/d48/classmimicpp_1_1_mock.html", null ]
    ] ],
    [ "mimicpp::detail::BasicMock< OtherSignatures >", null, [
      [ "mimicpp::Mock< void()>", "d2/d48/classmimicpp_1_1_mock.html", null ],
      [ "mimicpp::Mock< FirstSignature, OtherSignatures >", "d2/d48/classmimicpp_1_1_mock.html", null ]
    ] ],
    [ "mimicpp::detail::BasicMock< void() >", null, [
      [ "mimicpp::Mock< void()>", "d2/d48/classmimicpp_1_1_mock.html", null ]
    ] ],
    [ "mimicpp::sequence::detail::BasicSequenceInterface< sequence::Id, sequence::detail::GreedyStrategy{}>", null, [
      [ "mimicpp::GreedySequence", "db/d43/classmimicpp_1_1_greedy_sequence.html", null ]
    ] ],
    [ "mimicpp::sequence::detail::BasicSequenceInterface< sequence::Id, sequence::detail::LazyStrategy{}>", null, [
      [ "mimicpp::LazySequence", "db/d46/classmimicpp_1_1_lazy_sequence.html", null ]
    ] ],
    [ "std::bool_constant", null, [
      [ "mimicpp::always_false<... >", "d5/d8e/structmimicpp_1_1always__false.html", null ],
      [ "mimicpp::signature_is_noexcept< Signature >", "d9/d28/structmimicpp_1_1signature__is__noexcept.html", null ]
    ] ],
    [ "mimicpp::call_convention_traits< Tag >", "d3/db5/structmimicpp_1_1call__convention__traits.html", null ],
    [ "mimicpp::call_convention_traits< detail::default_call_convention >", "d3/db5/structmimicpp_1_1call__convention__traits.html", null ],
    [ "mimicpp::call_convention_traits< signature_call_convention_t< Signature > >", "d3/db5/structmimicpp_1_1call__convention__traits.html", null ],
    [ "mimicpp::CallReport", "dc/dd0/classmimicpp_1_1_call_report.html", null ],
    [ "mimicpp::case_insensitive_t", "d2/dd4/structmimicpp_1_1case__insensitive__t.html", null ],
    [ "mimicpp::expectation_policies::Category< expected >", "d4/d44/classmimicpp_1_1expectation__policies_1_1_category.html", null ],
    [ "std::conditional_t", null, [
      [ "mimicpp::detail::is_overloadable_with< detail::normalize_overload_t< First >, detail::normalize_overload_t< Second > >", null, [
        [ "mimicpp::is_overloadable_with< First, Second >", "d4/dd6/structmimicpp_1_1is__overloadable__with.html", null ]
      ] ]
    ] ],
    [ "std::conjunction", null, [
      [ "mimicpp::is_overload_set< First >", "dd/df5/structmimicpp_1_1is__overload__set.html", null ],
      [ "mimicpp::is_overload_set< First, Others >", "dd/df5/structmimicpp_1_1is__overload__set.html", null ]
    ] ],
    [ "mimicpp::expectation_policies::Constness< constness >", "db/dbc/classmimicpp_1_1expectation__policies_1_1_constness.html", null ],
    [ "mimicpp::ControlPolicy< Sequences >", "dc/db2/classmimicpp_1_1_control_policy.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "mimicpp::Error< std::tuple< CallReport, std::vector< MatchReport > > >", "db/d10/classmimicpp_1_1_error.html", null ],
        [ "mimicpp::Error< ExpectationReport >", "db/d10/classmimicpp_1_1_error.html", null ],
        [ "mimicpp::Error< Data >", "db/d10/classmimicpp_1_1_error.html", null ]
      ] ]
    ] ],
    [ "mimicpp::Expectation< Signature >", "d3/d1c/classmimicpp_1_1_expectation.html", [
      [ "mimicpp::BasicExpectation< Signature, ControlPolicy, FinalizePolicy, Policies >", "d3/d4a/classmimicpp_1_1_basic_expectation.html", null ]
    ] ],
    [ "mimicpp::MatchReport::Expectation", "da/d15/classmimicpp_1_1_match_report_1_1_expectation.html", null ],
    [ "mimicpp::ExpectationCollection< Signature >", "d5/d86/classmimicpp_1_1_expectation_collection.html", null ],
    [ "mimicpp::ExpectationReport", "dd/d62/classmimicpp_1_1_expectation_report.html", null ],
    [ "std::false_type", null, [
      [ "mimicpp::is_character< char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< char16_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< char32_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< char8_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< signed char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< unsigned char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< wchar_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< T >", "d2/d73/structmimicpp_1_1is__character.html", null ]
    ] ],
    [ "mimicpp::MatchReport::Finalize", "d5/d36/classmimicpp_1_1_match_report_1_1_finalize.html", null ],
    [ "mimicpp::stacktrace::find_backend", "dc/dc2/structmimicpp_1_1stacktrace_1_1find__backend.html", null ],
    [ "formatter", null, [
      [ "mimicpp::format::formatter< mimicpp::Constness, mimicpp::CharT >", "d2/d9b/structmimicpp_1_1format_1_1formatter_3_01mimicpp_1_1_constness_00_01mimicpp_1_1_char_t_01_4.html", null ],
      [ "mimicpp::format::formatter< mimicpp::ValueCategory, mimicpp::CharT >", "db/dc9/structmimicpp_1_1format_1_1formatter_3_01mimicpp_1_1_value_category_00_01mimicpp_1_1_char_t_01_4.html", null ]
    ] ],
    [ "mimicpp::call::Info< Return, Args >", "d4/d44/classmimicpp_1_1call_1_1_info.html", null ],
    [ "mimicpp::call::Info< Return, Args... >", "d4/d44/classmimicpp_1_1call_1_1_info.html", null ],
    [ "mimicpp::call::info_for_signature< Signature >", "d8/d5b/structmimicpp_1_1call_1_1info__for__signature.html", null ],
    [ "mimicpp::call::info_for_signature< Return(Args...)>", "d8/d5b/structmimicpp_1_1call_1_1info__for__signature.html", null ],
    [ "mimicpp::expectation_policies::InitFinalize", "d2/d77/classmimicpp_1_1expectation__policies_1_1_init_finalize.html", null ],
    [ "std::integral_constant", null, [
      [ "mimicpp::signature_const_qualification< Signature >", "d2/de2/structmimicpp_1_1signature__const__qualification.html", null ],
      [ "mimicpp::signature_ref_qualification< Return(Params...) && >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "mimicpp::signature_ref_qualification< Return(Params...)& >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "mimicpp::signature_ref_qualification< Return(Params...)>", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "mimicpp::signature_ref_qualification< Return(Params...,...) && >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "mimicpp::signature_ref_qualification< Return(Params...,...)& >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
      [ "mimicpp::signature_ref_qualification< Return(Params...,...)>", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ]
    ] ],
    [ "mimicpp::IReporter", "dd/df0/classmimicpp_1_1_i_reporter.html", [
      [ "mimicpp::BasicReporter< &detail::boost_test::send_success, &detail::boost_test::send_warning, &detail::boost_test::send_fail >", "d4/d56/classmimicpp_1_1_basic_reporter.html", null ],
      [ "mimicpp::BasicReporter< &detail::catch2::send_success, &detail::catch2::send_warning, &detail::catch2::send_fail >", "d4/d56/classmimicpp_1_1_basic_reporter.html", null ],
      [ "mimicpp::BasicReporter< &detail::doctest::send_success, &detail::doctest::send_warning, &detail::doctest::send_fail >", "d4/d56/classmimicpp_1_1_basic_reporter.html", null ],
      [ "mimicpp::BasicReporter< &detail::gtest::send_success, &detail::gtest::send_warning, &detail::gtest::send_fail >", "d4/d56/classmimicpp_1_1_basic_reporter.html", null ],
      [ "mimicpp::BasicReporter< successReporter, warningReporter, failReporter >", "d4/d56/classmimicpp_1_1_basic_reporter.html", null ],
      [ "mimicpp::DefaultReporter", "d3/d32/classmimicpp_1_1_default_reporter.html", null ]
    ] ],
    [ "mimicpp::LifetimeWatcher", "db/d98/classmimicpp_1_1_lifetime_watcher.html", null ],
    [ "mimicpp::expectation_policies::matcher_matches_fn< Matcher >", "d6/de9/structmimicpp_1_1expectation__policies_1_1matcher__matches__fn.html", null ],
    [ "mimicpp::custom::matcher_traits< Matcher >", "d5/d5a/structmimicpp_1_1custom_1_1matcher__traits.html", null ],
    [ "mimicpp::MatchReport", "db/d11/classmimicpp_1_1_match_report.html", null ],
    [ "mimicpp::stacktrace::NullBackend", "d0/d60/classmimicpp_1_1stacktrace_1_1_null_backend.html", null ],
    [ "mimicpp::PredicateMatcher< Predicate, AdditionalArgs >", "dc/d5e/classmimicpp_1_1_predicate_matcher.html", null ],
    [ "mimicpp::custom::Printer< typename >", "da/d68/classmimicpp_1_1custom_1_1_printer.html", null ],
    [ "mimicpp::priority_tag< priority >", "d1/d9f/structmimicpp_1_1priority__tag.html", null ],
    [ "mimicpp::priority_tag< 0 >", "d1/d9f/structmimicpp_1_1priority__tag.html", null ],
    [ "mimicpp::sequence::rating", "de/d81/structmimicpp_1_1sequence_1_1rating.html", null ],
    [ "mimicpp::RelocationWatcher", "da/d45/classmimicpp_1_1_relocation_watcher.html", null ],
    [ "mimicpp::expectation_policies::ReturnsResultOf< Action >", "dd/d59/classmimicpp_1_1expectation__policies_1_1_returns_result_of.html", null ],
    [ "mimicpp::ScopedExpectation", "d6/dc0/classmimicpp_1_1_scoped_expectation.html", null ],
    [ "mimicpp::expectation_policies::SideEffectAction< Action >", "d5/d8f/classmimicpp_1_1expectation__policies_1_1_side_effect_action.html", null ],
    [ "mimicpp::signature_add_noexcept< Signature >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) const & >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) const && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) const &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) const &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) const >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) const noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...) noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...)& >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...)>", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) const & >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) const && >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) const &&noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) const &noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) const >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) const noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...) noexcept >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...)& >", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_add_noexcept< Return(Params...,...)>", "dd/db4/structmimicpp_1_1signature__add__noexcept.html", null ],
    [ "mimicpp::signature_call_convention< Signature >", "dc/d9a/structmimicpp_1_1signature__call__convention.html", null ],
    [ "mimicpp::signature_call_convention< Signature >", "dc/d9a/structmimicpp_1_1signature__call__convention.html", null ],
    [ "mimicpp::signature_decay< Signature >", "db/df4/structmimicpp_1_1signature__decay.html", null ],
    [ "mimicpp::signature_param_list< Signature >", "d0/df4/structmimicpp_1_1signature__param__list.html", null ],
    [ "mimicpp::signature_param_list< Return(Params...)>", "d0/df4/structmimicpp_1_1signature__param__list.html", null ],
    [ "mimicpp::signature_param_type< index, Signature >", "db/dd5/structmimicpp_1_1signature__param__type.html", null ],
    [ "mimicpp::signature_ref_qualification< Signature >", "d7/d97/structmimicpp_1_1signature__ref__qualification.html", null ],
    [ "mimicpp::signature_remove_call_convention< Signature >", "dc/d70/structmimicpp_1_1signature__remove__call__convention.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Signature >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) const & >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) const && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) const &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) const &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) const >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) const noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...) noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...)& >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...)>", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) const & >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) const && >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) const &&noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) const &noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) const >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) const noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...) noexcept >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...)& >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Return(Params...,...)>", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_const_qualifier< Signature >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::signature_remove_noexcept< Signature >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) const & >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) const && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) const &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) const &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) const >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) const noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...) noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...)& >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...)>", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) const & >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) const && >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) const &&noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) const &noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) const >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) const noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...) noexcept >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...)& >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Return(Params...,...)>", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_noexcept< Signature >", "d4/db7/structmimicpp_1_1signature__remove__noexcept.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Signature >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) const & >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) const && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) const &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) const &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) const >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) const noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...) noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...)& >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...)>", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) const & >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) const && >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) const &&noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) const &noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) const >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) const noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...) noexcept >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...)& >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Return(Params...,...)>", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_remove_ref_qualifier< Signature >", "d5/dae/structmimicpp_1_1signature__remove__ref__qualifier.html", null ],
    [ "mimicpp::signature_return_type< Signature >", "d4/d96/structmimicpp_1_1signature__return__type.html", null ],
    [ "mimicpp::signature_return_type< Return(Params...)>", "d4/d96/structmimicpp_1_1signature__return__type.html", null ],
    [ "mimicpp::signature_return_type< Return(Params...,...)>", "d4/d96/structmimicpp_1_1signature__return__type.html", null ],
    [ "mimicpp::Stacktrace", "db/d18/classmimicpp_1_1_stacktrace.html", null ],
    [ "mimicpp::state_applicable", "d0/d12/structmimicpp_1_1state__applicable.html", null ],
    [ "mimicpp::state_inapplicable", "d7/dd2/structmimicpp_1_1state__inapplicable.html", null ],
    [ "mimicpp::state_saturated", "de/d68/structmimicpp_1_1state__saturated.html", null ],
    [ "mimicpp::string_case_fold_converter< Char >", "d4/d2d/structmimicpp_1_1string__case__fold__converter.html", null ],
    [ "mimicpp::string_case_fold_converter< char >", "d4/d2d/structmimicpp_1_1string__case__fold__converter.html", null ],
    [ "mimicpp::string_traits< T >", "d1/dee/structmimicpp_1_1string__traits.html", null ],
    [ "mimicpp::string_traits< std::basic_string< Char, Traits, Allocator > >", "d1/dee/structmimicpp_1_1string__traits.html", null ],
    [ "mimicpp::string_traits< std::basic_string_view< Char, Traits > >", "d1/dee/structmimicpp_1_1string__traits.html", null ],
    [ "mimicpp::string_traits< std::remove_extent_t< T > * >", "d1/dee/structmimicpp_1_1string__traits.html", [
      [ "mimicpp::string_traits< T >", "d1/dee/structmimicpp_1_1string__traits.html", null ]
    ] ],
    [ "mimicpp::expectation_policies::Throws< Exception >", "d8/d34/classmimicpp_1_1expectation__policies_1_1_throws.html", null ],
    [ "std::true_type", null, [
      [ "mimicpp::is_character< char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< char16_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< char32_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< char8_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< signed char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< unsigned char >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_character< wchar_t >", "d2/d73/structmimicpp_1_1is__character.html", null ],
      [ "mimicpp::is_overload_set< First >", "dd/df5/structmimicpp_1_1is__overload__set.html", null ]
    ] ],
    [ "std::tuple_element", null, [
      [ "mimicpp::signature_param_type< index, Return(Params...)>", "db/dd5/structmimicpp_1_1signature__param__type.html", null ]
    ] ],
    [ "mimicpp::type_list< Args >", "db/dc6/structmimicpp_1_1type__list.html", null ],
    [ "mimicpp::type_list< Params... >", "db/dc6/structmimicpp_1_1type__list.html", null ],
    [ "mimicpp::type_list< Uniques... >", "db/dc6/structmimicpp_1_1type__list.html", null ],
    [ "mimicpp::uint_with_size< byteCount >", "d7/da0/structmimicpp_1_1uint__with__size.html", null ],
    [ "mimicpp::uint_with_size< 1u >", "d7/da0/structmimicpp_1_1uint__with__size.html", null ],
    [ "mimicpp::uint_with_size< 2u >", "d7/da0/structmimicpp_1_1uint__with__size.html", null ],
    [ "mimicpp::uint_with_size< 4u >", "d7/da0/structmimicpp_1_1uint__with__size.html", null ],
    [ "mimicpp::uint_with_size< 8u >", "d7/da0/structmimicpp_1_1uint__with__size.html", null ],
    [ "Watchers...", null, [
      [ "mimicpp::detail::CombinedWatchers< Base, Watchers... >", null, [
        [ "mimicpp::detail::BasicWatched< Base, Watchers... >", null, null ],
        [ "mimicpp::detail::BasicWatched< Base, Watchers... >", null, null ]
      ] ]
    ] ],
    [ "mimicpp::WildcardMatcher", "db/de6/classmimicpp_1_1_wildcard_matcher.html", null ]
];