var searchData=
[
  ['c_2020_20modules_0',['Enable experimental C++20 modules.',['../d2/d65/group___c_o_n_f_i_g_u_r_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['call_20conventions_1',['Call-Conventions',['../index.html#autotoc_md63',1,'']]],
  ['case_20folding_2',['Case-Folding',['../d0/d65/group___m_a_t_c_h_e_r_s___s_t_r_i_n_g.html#autotoc_md4',1,'']]],
  ['case_20insensitive_20matchers_3',['Case-Insensitive Matchers',['../d0/d65/group___m_a_t_c_h_e_r_s___s_t_r_i_n_g.html#autotoc_md3',1,'']]],
  ['case_20insensitive_20matching_4',['Support for case-insensitive matching',['../d8/d47/group___s_t_r_i_n_g.html#autotoc_md22',1,'']]],
  ['catch2_20matcher_20integration_5',['Enable experimental catch2-matcher integration',['../d2/d65/group___c_o_n_f_i_g_u_r_a_t_i_o_n.html#autotoc_md32',1,'']]],
  ['char_20type_6',['Custom Strings with common char-type',['../d8/d47/group___s_t_r_i_n_g.html#autotoc_md19',1,'']]],
  ['char_20types_7',['Bring your own string- and char-types',['../index.html#autotoc_md62',1,'']]],
  ['char_20types_20and_20related_20strings_8',['Custom char-types and related strings',['../d8/d47/group___s_t_r_i_n_g.html#autotoc_md20',1,'']]],
  ['character_20types_9',['Strings with other character-types',['../d0/d65/group___m_a_t_c_h_e_r_s___s_t_r_i_n_g.html#autotoc_md6',1,'']]],
  ['clang_2018_201_20libc_10',['Clang-18.1 + libc++',['../index.html#autotoc_md76',1,'']]],
  ['cmake_11',['CMake',['../index.html#autotoc_md67',1,'']]],
  ['cmake_20usage_12',['Non-cmake usage',['../d2/d65/group___c_o_n_f_i_g_u_r_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['common_20char_20type_13',['Custom Strings with common char-type',['../d8/d47/group___s_t_r_i_n_g.html#autotoc_md19',1,'']]],
  ['constructor_20and_20assignment_20operator_14',['Move-constructor and -assignment-operator',['../d3/d5d/classmimicpp_1_1_watched.html#autotoc_md13',1,'']]],
  ['contents_15',['Table of Contents',['../index.html#autotoc_md51',1,'']]],
  ['conventions_16',['Call-Conventions',['../index.html#autotoc_md63',1,'']]],
  ['copying_17',['Copying',['../db/d98/classmimicpp_1_1_lifetime_watcher.html#autotoc_md10',1,'Copying'],['../da/d45/classmimicpp_1_1_relocation_watcher.html#autotoc_md12',1,'Copying']]],
  ['core_20design_18',['Core Design',['../index.html#autotoc_md54',1,'']]],
  ['custom_20char_20types_20and_20related_20strings_19',['Custom char-types and related strings',['../d8/d47/group___s_t_r_i_n_g.html#autotoc_md20',1,'']]],
  ['custom_20finalizers_20',['Custom Finalizers',['../db/d7a/group___e_x_p_e_c_t_a_t_i_o_n___f_i_n_a_l_i_z_e_r.html#autotoc_md15',1,'']]],
  ['custom_20matcher_21',['Custom Matcher',['../d4/d14/group___m_a_t_c_h_e_r_s.html#autotoc_md8',1,'']]],
  ['custom_20stacktrace_20backends_22',['Custom Stacktrace Backends',['../de/dc2/group___u_t_i_l___s_t_a_c_k_t_r_a_c_e.html#autotoc_md25',1,'']]],
  ['custom_20strings_20with_20common_20char_20type_23',['Custom Strings with common char-type',['../d8/d47/group___s_t_r_i_n_g.html#autotoc_md19',1,'']]],
  ['custom_20types_24',['Override existing printings or print custom types',['../d1/d07/group___p_r_i_n_t_i_n_g___s_t_a_t_e.html#autotoc_md16',1,'']]],
  ['customizability_25',['Features &amp;amp; Customizability',['../index.html#autotoc_md58',1,'']]],
  ['customize_20type_20stringification_26',['Customize type-stringification',['../df/d35/group___p_r_i_n_t_i_n_g___t_y_p_e.html#autotoc_md18',1,'']]]
];
