var group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r =
[
    [ "is_overload_set", "df/dc6/group___t_y_p_e___t_r_a_i_t_s___i_s___o_v_e_r_l_o_a_d___s_e_t.html", "df/dc6/group___t_y_p_e___t_r_a_i_t_s___i_s___o_v_e_r_l_o_a_d___s_e_t" ],
    [ "is_overloadable_with", "d1/d9e/group___t_y_p_e___t_r_a_i_t_s___i_s___o_v_e_r_l_o_a_d_a_b_l_e___w_i_t_h.html", "d1/d9e/group___t_y_p_e___t_r_a_i_t_s___i_s___o_v_e_r_l_o_a_d_a_b_l_e___w_i_t_h" ],
    [ "signature_const_qualification", "da/dc2/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___c_o_n_s_t___q_u_a_l_i_f_i_c_a_t_i_o_n.html", "da/dc2/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___c_o_n_s_t___q_u_a_l_i_f_i_c_a_t_i_o_n" ],
    [ "signature_decay", "d6/da6/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___d_e_c_a_y.html", "d6/da6/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___d_e_c_a_y" ],
    [ "signature_param_list", "d3/dce/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___p_a_r_a_m___l_i_s_t.html", "d3/dce/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___p_a_r_a_m___l_i_s_t" ],
    [ "signature_param_type", "dd/df9/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___p_a_r_a_m___t_y_p_e.html", "dd/df9/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___p_a_r_a_m___t_y_p_e" ],
    [ "signature_ref_qualification", "db/d91/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_f___q_u_a_l_i_f_i_c_a_t_i_o_n.html", "db/d91/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_f___q_u_a_l_i_f_i_c_a_t_i_o_n" ],
    [ "signature_return_type", "d0/d3b/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_t_u_r_n___t_y_p_e.html", "d0/d3b/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_t_u_r_n___t_y_p_e" ],
    [ "uint_with_size", "db/d34/group___t_y_p_e___t_r_a_i_t_s___u_i_n_t___w_i_t_h___s_i_z_e.html", "db/d34/group___t_y_p_e___t_r_a_i_t_s___u_i_n_t___w_i_t_h___s_i_z_e" ],
    [ "mimicpp::signature_remove_const_qualifier< Signature >", "d8/de6/structmimicpp_1_1signature__remove__const__qualifier.html", null ],
    [ "mimicpp::call_convention_traits< detail::default_call_convention >::add_call_convention_t", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga8aaaa02958d794699258c27f8bf468dd", null ],
    [ "mimicpp::call_convention_traits< detail::default_call_convention >::call_interface_t", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga82adaf43a6f88ca139fc9ff922119441", null ],
    [ "mimicpp::call_convention_traits< detail::default_call_convention >::remove_call_convention_t", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#gae9bf33737a7f5a7e6e6252b4c4dfd5d4", null ],
    [ "mimicpp::signature_remove_const_qualifier_t", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#gab0af26fdf255fe11835f816be27c9f35", null ],
    [ "mimicpp::call_convention_traits< detail::default_call_convention >::tag_t", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#gaddddf8af9c1dca219b021607824b0775", null ],
    [ "mimicpp::signature_call_convention< Signature >::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga0f54c01510f88e759532968e5af6ccbc", null ],
    [ "mimicpp::signature_decay::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#gab7cd71c1e5587ea9e2cdfe43a91a3152", null ],
    [ "mimicpp::signature_param_list< Return(Params...)>::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga967b718b7319e2ca11035549b39c003a", null ],
    [ "mimicpp::signature_remove_call_convention::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga981cda6f9bb53ed6ee1daa5a7fb2486f", null ],
    [ "mimicpp::signature_return_type< Return(Params...)>::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga1d69e687d4cad1aca48534aff5c18e09", null ],
    [ "mimicpp::signature_return_type< Return(Params...,...)>::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#gaae2462c73bdababb0806c9d47efba9a3", null ],
    [ "mimicpp::uint_with_size< 1u >::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga7f8ddb0c20e95f3add9056e351984005", null ],
    [ "mimicpp::uint_with_size< 2u >::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga1087b04b099a74a359bf025a33dde0c3", null ],
    [ "mimicpp::uint_with_size< 4u >::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#gae44882b5ea4ca17ab16f2f94c670f9e1", null ],
    [ "mimicpp::uint_with_size< 8u >::type", "d3/def/group___t_y_p_e___t_r_a_i_t_s___s_i_g_n_a_t_u_r_e___r_e_m_o_v_e___c_o_n_s_t___q_u_a_l_i_f_i_e_r.html#ga7f777d6e66976ce6720af6ecce4754a9", null ]
];